version: '3'
services:
  renderserver:
    build: ./rawflash
    ports:
     - "4000:4000"
  client:
    build: ./testclient
    ports:
      - "80:80"
    volumes:
      - ./testclient/src:/usr/share/nginx/html
